#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v20
# autospec commit: f35655a
#
Name     : intel-ipsec-mb
Version  : 2.0
Release  : 21
URL      : https://github.com/intel/intel-ipsec-mb/archive/v2.0/intel-ipsec-mb-2.0.tar.gz
Source0  : https://github.com/intel/intel-ipsec-mb/archive/v2.0/intel-ipsec-mb-2.0.tar.gz
Summary  : IPSEC cryptography library optimized for Intel Architecture
Group    : Development/Tools
License  : BSD-3-Clause
Requires: intel-ipsec-mb-lib = %{version}-%{release}
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : nasm
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
IPSEC cryptography library optimized for Intel Architecture

%package dev
Summary: dev components for the intel-ipsec-mb package.
Group: Development
Requires: intel-ipsec-mb-lib = %{version}-%{release}
Provides: intel-ipsec-mb-devel = %{version}-%{release}
Requires: intel-ipsec-mb = %{version}-%{release}

%description dev
dev components for the intel-ipsec-mb package.


%package lib
Summary: lib components for the intel-ipsec-mb package.
Group: Libraries

%description lib
lib components for the intel-ipsec-mb package.


%prep
%setup -q -n intel-ipsec-mb-2.0
cd %{_builddir}/intel-ipsec-mb-2.0
%patch -P 1 -p1
pushd ..
cp -a intel-ipsec-mb-2.0 buildavx2
popd
pushd ..
cp -a intel-ipsec-mb-2.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1730737274
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64
popd
pushd ../buildavx512
GOAMD64=v4
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v4 -mprefer-vector-width=256 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v4 "
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1730737274
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64
popd
GOAMD64=v4
pushd ../buildavx512/
%make_install_v4 NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64
popd
GOAMD64=v2
%make_install NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64
## install_append content
#mkdir -p %{buildroot}/usr/lib64
#mkdir -p %{buildroot}-v3/usr/lib64
#mkdir -p %{buildroot}-v4/usr/lib64
#mv %{buildroot}/usr/lib/* %{buildroot}/usr/lib64
#mv %{buildroot}-v3/usr/lib/* %{buildroot}-v3/usr/lib64
#mv %{buildroot}-v4/usr/lib/* %{buildroot}-v4/usr/lib64
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/man/man7/libipsec-mb-dev.7
/usr/man/man7/libipsec-mb.7

%files dev
%defattr(-,root,root,-)
/usr/include/intel-ipsec-mb.h
/usr/lib64/libIPSec_MB.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libIPSec_MB.so.2.0.0
/V4/usr/lib64/libIPSec_MB.so.2.0.0
/usr/lib64/libIPSec_MB.so.2
/usr/lib64/libIPSec_MB.so.2.0.0
