#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : intel-ipsec-mb
Version  : 1.4
Release  : 16
URL      : https://github.com/intel/intel-ipsec-mb/archive/v1.4/intel-ipsec-mb-1.4.tar.gz
Source0  : https://github.com/intel/intel-ipsec-mb/archive/v1.4/intel-ipsec-mb-1.4.tar.gz
Summary  : IPSEC cryptography library optimized for Intel Architecture
Group    : Development/Tools
License  : BSD-3-Clause
Requires: intel-ipsec-mb-lib = %{version}-%{release}
Requires: intel-ipsec-mb-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : nasm
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
IPSEC cryptography library optimized for Intel Architecture

%package dev
Summary: dev components for the intel-ipsec-mb package.
Group: Development
Requires: intel-ipsec-mb-lib = %{version}-%{release}
Provides: intel-ipsec-mb-devel = %{version}-%{release}
Requires: intel-ipsec-mb = %{version}-%{release}

%description dev
dev components for the intel-ipsec-mb package.


%package lib
Summary: lib components for the intel-ipsec-mb package.
Group: Libraries
Requires: intel-ipsec-mb-license = %{version}-%{release}

%description lib
lib components for the intel-ipsec-mb package.


%package license
Summary: license components for the intel-ipsec-mb package.
Group: Default

%description license
license components for the intel-ipsec-mb package.


%prep
%setup -q -n intel-ipsec-mb-1.4
cd %{_builddir}/intel-ipsec-mb-1.4
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686875621
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export CFLAGS="$CFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FFLAGS="$FFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FCFLAGS="$FCFLAGS -march=x86-64-v4 -m64 "
%cmake ..
make  %{?_smp_mflags}  SAFE_DATA=y SAFE_PARAM=y SAFE_LOOKUP=y LIB_INSTALL_DIR=/usr/lib64
popd

%install
export SOURCE_DATE_EPOCH=1686875621
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/intel-ipsec-mb
cp %{_builddir}/intel-ipsec-mb-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/intel-ipsec-mb/39a580dee5b6c1f66b7a255a7dfde5219b19d985 || :
pushd clr-build-avx2
%make_install_v3 NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64 || :
popd
pushd clr-build-avx512
%make_install_v4 NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64 || :
popd
pushd clr-build
%make_install NOLDCONFIG=y LIB_INSTALL_DIR=/usr/lib64
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64
mkdir -p %{buildroot}-v3/usr/lib64
mkdir -p %{buildroot}-v4/usr/lib64
mv %{buildroot}/usr/lib/* %{buildroot}/usr/lib64
mv %{buildroot}-v3/usr/lib/* %{buildroot}-v3/usr/lib64
mv %{buildroot}-v4/usr/lib/* %{buildroot}-v4/usr/lib64
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/man/man7/libipsec-mb-dev.7
/usr/man/man7/libipsec-mb.7

%files dev
%defattr(-,root,root,-)
/usr/lib64/libIPSec_MB.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libIPSec_MB.so.1.4.0
/V4/usr/lib64/libIPSec_MB.so.1.4.0
/usr/lib64/libIPSec_MB.so.1
/usr/lib64/libIPSec_MB.so.1.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/intel-ipsec-mb/39a580dee5b6c1f66b7a255a7dfde5219b19d985
